version: 2

aliases:
  - &filter-only-master
    branches:
      only:
        - master
  - &filter-ignore-master
    branches:
      ignore:
        - master

defaults: &defaults
  docker:
    - image: circleci/node:10
  working_directory: ~/react-native-testing-library

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-native-testing-library
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile --no-progress --non-interactive --cache-folder ~/.cache/yarn
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint-and-flow:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-native-testing-library
      - run: |
          yarn lint
          yarn flow-check
  typescript:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-native-testing-library
      - run: |
          yarn typescript-check
  tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-native-testing-library
      - run: yarn test
      - store_artifacts:
          path: coverage
          destination: coverage
  test-website:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-native-testing-library
      - run: |
          cd website && yarn install && yarn build
  test-examples:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-native-testing-library
      - run: |
          cd examples/reactnavigation && yarn install && yarn test
      - run: |
          cd examples/redux && yarn install && yarn test
  deploy-website:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "thymikee@users.noreply.github.com"
            git config --global user.name "Michał Pierzchała"
            echo "machine github.com login thymikee password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=thymikee yarn deploy

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - lint-and-flow:
          requires:
            - install-dependencies
      - typescript:
          requires:
            - install-dependencies
      - tests:
          requires:
            - install-dependencies
      - test-website:
          requires:
            - install-dependencies
          # docusuarus build is running when deploying website as well
          filters: *filter-ignore-master
      - test-examples:
          requires:
            - install-dependencies
          filters: *filter-only-master
      - deploy-website:
          requires:
            - install-dependencies
          filters: *filter-only-master
