version: 2.1

aliases:
  - &filter-only-main
    branches:
      only:
        - main
  - &filter-ignore-main
    branches:
      ignore:
        - main

defaults: &defaults
  docker:
    - image: cimg/node:current
  working_directory: ~/react-native-testing-library

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/react-native-testing-library
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile --no-progress --non-interactive --cache-folder ~/.cache/yarn
      - save_cache:
          key: dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
  lint-and-typescript:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-native-testing-library
      - run: |
          yarn lint
          yarn typecheck
  flow:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-native-testing-library
      - run: |
          yarn flow
  tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-native-testing-library
      - run: yarn test:ci
      - store_artifacts:
          path: coverage
          destination: coverage
      - codecov/upload:
          file: coverage
  test-react-17:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-native-testing-library
      - run: |
          yarn test:ci:react:17
  test-website:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/react-native-testing-library
      - run: |
          cd website && yarn install && yarn build
  run-coverage:
    <<: *defaults
    steps:
      - codecov/upload:
          file: coverage
  deploy-website:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "thymikee@users.noreply.github.com"
            git config --global user.name "Michał Pierzchała"
            echo "machine github.com login thymikee password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=thymikee yarn deploy

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - lint-and-typescript:
          requires:
            - install-dependencies
      - flow:
          requires:
            - install-dependencies
      - tests:
          requires:
            - install-dependencies
      - test-react-17:
          requires:
            - install-dependencies
      - test-website:
          requires:
            - install-dependencies
          # docusuarus build is running when deploying website as well
          filters: *filter-ignore-main
      - deploy-website:
          requires:
            - install-dependencies
          filters: *filter-only-main
      - run-coverage:
          requires:
            - install-dependencies
            - tests